export const eventsData = [
    {
        id: 8,
        title: "Conquer Mount Sabyinyo",
        subtitle: "Stand at the summit of Rwanda, Uganda & DR Congo in one unforgettable climb",
        description: "Leave the city behind and reach the summit of one of Rwanda’s most iconic peaks. Are you ready for the ultimate 3,669 m challenge? Experience a safe, well-organized guided trek with expert guides in a small group. Limited bookings - reserve your spot today.",
        date: "20 June 2026",
        time: "Early Morning Departure from Kigali",
        fees: "Rwandans: 50,000 RWF | Africans: $100 | Internationals: $130",
        lunch: "Meals, Water & Juice Included",
        transport: "+250 783 482 368",
        accommodation: "Transport from Kigali to Musanze & Return, Expert Guides, Meals, Water & Juice Included",
        image: "/assets/Events/newEvent8.jpeg",
        accent: "Sabyinyo",
        whatsapp: "250783482368"
    },
    {
        id: 4,
        title: "Ladies Safari Game Drive Experience at Akagera",
        subtitle: "An exclusive safari adventure tailored for women explorers",
        description: "Celebrate sisterhood while discovering Rwanda's iconic wildlife! This ladies safari package includes permits, guide, round transport, a 4x4 safari car with 7 seats, water, lunch, photographer, and gin or wine.",
        date: "Upcoming Dates Available",
        time: "Early Morning Departure from Kigali",
        fees: "International: $200 / \u20AC180 per person",
        lunch: "Water, Lunch, Photographer, Gin or Wine Included",
        transport: "+250 783 482 368",
        accommodation: "Permits, Guide, Round Transport, 4x4 Safari Car (7 Seats), Water, Lunch, Photographer, Gin or Wine",
        image: "/assets/Events/newEvent4.jpeg",
        accent: "Ladies",
        whatsapp: "250783482368"
    },
    {
        id: 5,
        title: "Buddies Private Safari Game Drive Experience at Akagera",
        subtitle: "Adventure with your best friends in the heart of the savannah",
        description: "Bring your squad and create unforgettable memories together! This private safari experience is designed for groups of friends seeking exclusive game drives, professional photography, and premium service. Spot the Big Five while enjoying quality time with your closest companions.",
        date: "Upcoming Dates Available",
        time: "Flexible Group Departure",
        fees: "International: $200 | $180 per person",
        lunch: "Lunch, Water, Gin/Wine & Photographer Included",
        transport: "+250 783 482 368",
        accommodation: "4x4 Safari Car (7 Seats), Permits, Guide, Round Transport & All Refreshments",
        image: "/assets/Events/newEvent5.jpeg",
        accent: "Group",
        whatsapp: "250783482368"
    },
    {
        id: 6,
        title: "Besties Private Safari Game Drive Experience at Akagera",
        subtitle: "Your special group's exclusive journey through Rwanda's premier national park",
        description: "Experience the ultimate safari with your besties! Enjoy a private 4x4 safari car, professional photography services, gourmet lunch, and premium refreshments. This tailored adventure ensures you and your group experience Akagera's wildlife in comfort and style.",
        date: "Upcoming Dates Available",
        time: "Flexible Group Departure",
        fees: "Rwandans: 150,000 RWF per person",
        lunch: "Lunch, Water, Gin/Wine & Photographer Included",
        transport: "+250 783 482 368",
        accommodation: "4x4 Safari Car (7 Seats), Permits, Guide, Round Transport & All Refreshments",
        image: "/assets/Events/newEvent6.jpeg",
        accent: "Friends",
        whatsapp: "250783482368"
    },
    {
        id: 7,
        title: "Abajama Private Safari Game Drive Experience at Akagera",
        subtitle: "A premium safari adventure for groups seeking immersive wildlife experiences",
        description: "Discover Rwanda's rich wildlife heritage on this exclusive private safari. The Abajama package offers a fully curated experience with premium 4x4 transportation, expert guides, professional photography, and authentic Rwandan hospitality. Perfect for family groups or close-knit communities.",
        date: "Upcoming Dates Available",
        time: "Flexible Group Departure",
        fees: "Rwandans: 150,000 RWF per person",
        lunch: "Lunch, Water, Gin/Wine & Photographer Included",
        transport: "+250 783 482 368",
        accommodation: "4x4 Safari Car (7 Seats), Permits, Guide, Round Transport & All Refreshments",
        image: "/assets/Events/newEvent7.jpeg",
        accent: "Heritage",
        whatsapp: "250783482368"
    },
    {
        id: 10,
        title: "Adventure in Nyungwe National Park",
        subtitle: "Zipline, Canopy Walk, Waterfall Hiking & Birdwatching in the Heart of the Forest",
        description: "Experience the thrill of Nyungwe's iconic zipline, walk the legendary canopy bridge, hike to breathtaking waterfalls, and discover rare bird species. A full day of adventure in Rwanda's most biodiverse forest.",
        date: "06 June 2026",
        time: "Early Morning Departure from Kigali",
        fees: "Rwandans & EAC: 65,000 RWF | Residents: $240 | Internationals: $300",
        lunch: "Lunch & Soft Drinks Included",
        transport: "+250 783 482 368",
        accommodation: "Transport, Entrance Fees, Permit Fees, Soft Drinks & Lunch Included",
        image: "/assets/Events/newEvent10.jpeg",
        accent: "Nyungwe",
        whatsapp: "250783482368"
    },
    {
        id: 12,
        title: "Conquer Mount Bisoke — The Crater Lake Awaits",
        subtitle: "Leave the city behind and reach the summit of one of Rwanda’s most iconic peaks",
        description: "Are you ready for the ultimate 3,711 m challenge? Climb Mount Bisoke, discover the stunning crater lake at the summit, and experience a safe, well-organized guided trek in a small group. Limited bookings - reserve your spot today.",
        date: "01 August 2026",
        time: "Early Morning Departure from Kigali",
        fees: "Rwandans: 50,000 RWF | Africans: $100 | Internationals: $130",
        lunch: "Meals, Water & Juice Included",
        transport: "+250 783 482 368",
        accommodation: "Transport from Kigali to Musanze & Return, Professional Guide, Meals, Water & Juice Included",
        image: "/assets/Events/eventshya.jpeg",
        accent: "Bisoke",
        whatsapp: "250783482368"
    }
];

