export const eventsData = [
    {
        id: 1,
        title: "It's Labor Day! Let's Go on an Akagera Safari Adventure!",
        subtitle: "Embark Your Lifetime Safari Journey to Akagera National Park",
        description: "Discover the Big Five in the heart of the savannah! Trade the office for the wild this Labor Day. Experience an unforgettable game drive through Akagera National Park with professional guides, photography services, and the opportunity to network with fellow adventure seekers.",
        date: "01 May 2026",
        time: "Early Morning Departure from Kigali",
        fees: "Rwandans: 50,000 RWF | Africans: $100 | Internationals: $150",
        lunch: "Lunch & Professional Guide Included",
        transport: "+250 783 482 368",
        accommodation: "Transport, Park Permit, Lunch & Photographer Included",
        image: "/assets/Events/newEvent.jpeg",
        accent: "Safari",
        whatsapp: "250783482368"
    },
    {
        id: 2,
        title: "Celebrate Labor Day in Akagera with a Safari Adventure",
        subtitle: "Corporate Safari Experience at Akagera National Park",
        description: "Hard work deserves a great escape! Join us for a corporate safari adventure where you'll discover the Big Five, enjoy networking opportunities, and create lasting memories. Optional upgrade available: Experience the savannah in style with our premium 4x4 safari car service.",
        date: "01 May 2026",
        time: "Organized Corporate Group Departure",
        fees: "Rwandans: 50,000 RWF | Africans: $100 | Internationals: $150",
        lunch: "Lunch & Professional Guide Included",
        transport: "+250 783 482 368",
        accommodation: "Transport, Park Permit, Lunch & Photographer Included (4x4 upgrade available)",
        image: "/assets/Events/newEvent2.jpeg",
        accent: "Corporate",
        whatsapp: "250783482368"
    },
    {
        id: 3,
        title: "Conquer Mount Bisoke - The Crater Lake Awaits",
        subtitle: "Leave the city behind and reach the summit of one of Rwanda's most iconic peaks",
        description: "Are you ready for the ultimate 3,711m challenge? Ascend Rwanda's most majestic volcanic peak and discover the breathtaking crater lake at the summit. This guided high-altitude trek offers photography opportunities to last a lifetime with stunning panoramic views of the surrounding landscape.",
        date: "09 May 2026",
        time: "Early Morning Departure from Kigali",
        fees: "Rwandans: 50,000 RWF | Africans: $100 | Internationals: $130",
        lunch: "Meals, Water, Juice & Banana Included",
        transport: "+250 783 482 368",
        accommodation: "Transport from Kigali to Musanze, Professional Guide & Meals Included",
        image: "/assets/Events/newEvent3.jpeg",
        accent: "Hiking",
        whatsapp: "250783482368"
    },
    {
        id: 4,
        title: "Ladies Safari Game Drive Experience at Akagera",
        subtitle: "An exclusive safari adventure tailored for women explorers",
        description: "Celebrate sisterhood while discovering Rwanda's iconic wildlife! This exclusive ladies-only safari features game drives in a premium 4x4 safari car, professional photography, refreshments, and a delicious lunch. Perfect for solo travelers, friends, or colleagues seeking an empowering wildlife adventure.",
        date: "Upcoming Dates Available",
        time: "Early Morning Departure from Kigali",
        fees: "International: $200 | $180 per person",
        lunch: "Lunch, Water, Gin/Wine & Photographer Included",
        transport: "+250 783 482 368",
        accommodation: "4x4 Safari Car (7 Seats), Permits, Guide, Round Transport & All Refreshments",
        image: "/assets/Events/newEvent4.jpeg",
        accent: "Ladies",
        whatsapp: "250783482368"
    },
    {
        id: 5,
        title: "Buddies Private Safari Game Drive Experience at Akagera",
        subtitle: "Adventure with your best friends in the heart of the savannah",
        description: "Bring your squad and create unforgettable memories together! This private safari experience is designed for groups of friends seeking exclusive game drives, professional photography, and premium service. Spot the Big Five while enjoying quality time with your closest companions.",
        date: "Upcoming Dates Available",
        time: "Flexible Group Departure",
        fees: "International: $200 | $180 per person",
        lunch: "Lunch, Water, Gin/Wine & Photographer Included",
        transport: "+250 783 482 368",
        accommodation: "4x4 Safari Car (7 Seats), Permits, Guide, Round Transport & All Refreshments",
        image: "/assets/Events/newEvent5.jpeg",
        accent: "Group",
        whatsapp: "250783482368"
    },
    {
        id: 6,
        title: "Besties Private Safari Game Drive Experience at Akagera",
        subtitle: "Your special group's exclusive journey through Rwanda's premier national park",
        description: "Experience the ultimate safari with your besties! Enjoy a private 4x4 safari car, professional photography services, gourmet lunch, and premium refreshments. This tailored adventure ensures you and your group experience Akagera's wildlife in comfort and style.",
        date: "Upcoming Dates Available",
        time: "Flexible Group Departure",
        fees: "Rwandans: 150,000 RWF per person",
        lunch: "Lunch, Water, Gin/Wine & Photographer Included",
        transport: "+250 783 482 368",
        accommodation: "4x4 Safari Car (7 Seats), Permits, Guide, Round Transport & All Refreshments",
        image: "/assets/Events/newEvent6.jpeg",
        accent: "Friends",
        whatsapp: "250783482368"
    },
    {
        id: 7,
        title: "Abajama Private Safari Game Drive Experience at Akagera",
        subtitle: "A premium safari adventure for groups seeking immersive wildlife experiences",
        description: "Discover Rwanda's rich wildlife heritage on this exclusive private safari. The Abajama package offers a fully curated experience with premium 4x4 transportation, expert guides, professional photography, and authentic Rwandan hospitality. Perfect for family groups or close-knit communities.",
        date: "Upcoming Dates Available",
        time: "Flexible Group Departure",
        fees: "Rwandans: 150,000 RWF per person",
        lunch: "Lunch, Water, Gin/Wine & Photographer Included",
        transport: "+250 783 482 368",
        accommodation: "4x4 Safari Car (7 Seats), Permits, Guide, Round Transport & All Refreshments",
        image: "/assets/Events/newEvent6.jpeg",
        accent: "Heritage",
        whatsapp: "250783482368"
    }
];
